### ISSUE TITLE
How can I upgrade tiller on ACS?

### ISSUE THREAD

**Issue by bacongobbler** [Azure/ACS#55]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Every time I try to bump the tiller version up to v2.6.0 in ACS, ACS keeps preventing that by re-deploying tiller v2.5.1, which is what was provided when bootstrapping the cluster. I'd like to upgrade tiller on my cluster, but I cannot do that without switching over to acs-engine to deploy a cluster.

**Comment by JackQuincy** [comment]
This appears to be because of how we are defining our tiller addon. We have it marked as a cluster service. Which means Kuberentes doesn't want to allow updates to it through the kubernetes api. Instead it wants the updates to happen on the file in the master. We could change to using addonmanager.kubernetes.io/mode=EnsureExists .  @anhowe @seanknox  @jackfrancis  thoughts?

relevant Kubernetes documentation 
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/README.md

**Comment by seanknox** [comment]
`addonmanager.kubernetes.io/mode=EnsureExists` appears to be right call here. Agree @lachie83?

**Comment by JackQuincy** [comment]
Also what do we think about doing this for dashboard, heapster, and the storage classes addons?  Do we want them static or do we want customers to be able to modify them through the api server

**Comment by seanknox** [comment]
Good call for dashboard and heapster, though my hunch without thinking through much is that we should err on the more prescriptive end with storage classes.

**Comment by JackQuincy** [comment]
I think I agree on not letting people shoot themselves in the foot with storage classes. Mostly I was wanting to look at all the extensions and decide if we want to update them while doing this.

**Comment by JackQuincy** [comment]
@bacongobbler if it wasn't clear there is a work around by updating the add-on file for tiller, /etc/kubernetes/addons/kube-tiller-deployment.yaml, to be the newer spec for tiller on each master.

**Comment by lachie83** [comment]
Confirming everything @JackQuincy @seanknox have said.

**Comment by bacongobbler** [comment]
I was able to work around this by deploying a hacked up acs-engine cluster with Tiller v2.6.0 but I'll keep that in mind for next time. Thanks @JackQuincy @seanknox @lachie83 for your help!

**Comment by berndverst** [comment]
Documenting my single command workaround based on comments above (make sure to replace the host with your ACS master node)
```
ssh azureuser@draftdeploymgmt.westus.cloudapp.azure.com sudo sed -i s/'2.5.1'/'2.6.0'/g /etc/kubernetes/addons/kube-tiller-deployment.yaml && helm init --upgrade
```

**Comment by bacongobbler** [comment]
@berndverst I tried your example and it worked, however I would suggest restarting the kube-addon-manager pod by deleting it from the kube-system namespace, e.g.

```
$ kubectl -n kube-system delete po kube-addon-manager-k8s-master-a637ed6-0
```

This will force a new addon-manager pod to boot and reconcile all the resources managed by the addon manager... Including tiller. This will force a fresh tiller v2.6.0 instance to be deployed.

**Comment by seanknox** [comment]
JFYI we have the long-term fix for this slated to go into acs-engine soon: https://github.com/Azure/acs-engine/pull/1319

**Comment by stuartleeks** [comment]
What is the timeline for this being fixed in ACS?

**Comment by JackQuincy** [comment]
It will be in the v2 regions in a week or two if it isn't already.  In the v1 regions it will be next month.

**Comment by subho007** [comment]
Any updates on this?

**Comment by JackQuincy** [comment]
Definetly in ACSv2. V1 is still a ways out we have had a deployment having other issues that is delaying this some.

**Comment by lrills** [comment]
Any update on this? Cluster in Southeast Asia still can't upgrade with `helm init --upgade` now.

**Comment by berndverst** [comment]
@lrills I manually had to update the add on definition on the Kubernetes master again as a workaround. Like so:
```
ssh azureuser@MYK8SMASTERHOST.westus.cloudapp.azure.com sudo sed -i s/'2.6.0'/'2.7.0'/g /etc/kubernetes/addons/kube-tiller-deployment.yaml && helm init --upgrade
```

No other method has reliably worked for me.

**Comment by bacongobbler** [comment]
I’m going to reopen this for visibility. I’m still making weekly references to this ticket in #helm-users. :)
